import "shared";

let base = "http://localhost:8080";

rq get_basic("{{base}}/test");
rq shared_with_env("{{base_url}}{{api_path}}");

[timeout(2)]
rq get_with_headers(
    "{{base}}/test",
    [
        "Accept": "application/json",
        "X-Uat": "basic",
    ]
);

[method(POST)]
rq post_json(
    "{{base}}/test",
    [
        "X-Uat": "post-json",
    ],
    ${"hello":"world","n":123}
);

rq post_text(
    url: "{{base}}/test",
    headers: [
        "Content-Type": "text/plain",
        "X-Uat": "post-text",
    ],
    body: "hello"
);
