let base = "http://localhost:8080";
let default_headers = [
    "X-Uat": "endpoint",
];

let user_id = "123";

ep api(url: base, headers: default_headers, qs: "v=1");

ep users<api>("{{base}}/users") {
    rq list();
    rq get(user_id);
}
