auth oauth_cc_cert(auth_type.oauth2_client_credentials) {
    client_id: "{{oauth_cc_cert_client_id}}",
    token_url: "{{oauth_token_url}}",
    cert_file: "../scripts/keycloak/uat/generated/rq-uat-cc-cert.p12",
    cert_password: "{{oauth_cc_cert_password}}",
    scope: "{{oauth_scope}}"
}

[auth("oauth_cc_cert")]
rq get_cc_cert("http://localhost:8080/test");
