auth oauth_cc(auth_type.oauth2_client_credentials) {
    client_id: "{{oauth_client_id}}",
    client_secret: "{{oauth_client_secret}}",
    token_url: "{{oauth_token_url}}",
    scope: "{{oauth_scope}}"
}

[auth("oauth_cc")]
rq get_cc_protected("http://localhost:8080/test");
