name: Publish Extension to Marketplace

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Download VSIX from latest release_prod
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: release_prod.yaml
          workflow_conclusion: success
          name: vscode-extension-vsix
          path: extension-artifact
          check_artifacts: true
          search_artifacts: true

      - name: Display downloaded files
        run: ls -R extension-artifact

      - name: Publish to VS Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.MARKETPLACE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: extension-artifact/**/*.vsix
